# Form implementation generated from reading ui file 'qml/main_window2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NETman(object):
    def setupUi(self, NETman):
        NETman.setObjectName("NETman")
        NETman.resize(760, 600)
        NETman.setMinimumSize(QtCore.QSize(760, 600))
        NETman.setMaximumSize(QtCore.QSize(760, 600))
        NETman.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        NETman.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        NETman.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=NETman)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.mainTabWidget.setTabsClosable(True)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.verticalLayout.addWidget(self.mainTabWidget)
        NETman.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NETman)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        NETman.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NETman)
        self.statusbar.setObjectName("statusbar")
        NETman.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=NETman)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(parent=NETman)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew_Tab = QtGui.QAction(parent=NETman)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.menuFile.addAction(self.actionNew_Tab)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(NETman)
        QtCore.QMetaObject.connectSlotsByName(NETman)

    def retranslateUi(self, NETman):
        _translate = QtCore.QCoreApplication.translate
        NETman.setWindowTitle(_translate("NETman", "NETman"))
        self.menuFile.setTitle(_translate("NETman", "File"))
        self.menuHelp.setTitle(_translate("NETman", "Help"))
        self.actionExit.setText(_translate("NETman", "Exit"))
        self.actionAbout.setText(_translate("NETman", "Documentation"))
        self.actionNew_Tab.setText(_translate("NETman", "New Tab"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NETman = QtWidgets.QMainWindow()
    ui = Ui_NETman()
    ui.setupUi(NETman)
    NETman.show()
    sys.exit(app.exec())
